### ISSUE TITLE
添加Openwrt支持

### ISSUE THREAD

**Issue by dysf888** [Misaka-blog/Misaka-WARP-Script#1]
或者windows也行
运营商只有v4连v6老麻烦了

**Comment by Lemonawa** [comment]
Openwrt=Linux
Linux=可以安装

**Comment by dysf888** [comment]
> Openwrt=Linux Linux=可以安装

![image](https://user-images.githubusercontent.com/47450409/164260590-b31fb1c9-d230-45ba-8372-f90843300185.png)

**Comment by Lemonawa** [comment]
@York618 对吼

**Comment by dysf888** [comment]
> Openwrt=Linux Linux=可以安装

X86 软路由

**Comment by York618** [comment]
@dysf888 x86？我去，肯定支持
但有嘛用？局域网搭个毛线宝塔/v2ray

**Comment by Lemonawa** [comment]
国内网络用啥warp啊
就算连的上
网络也稀烂

**Comment by dysf888** [comment]
> @dysf888 x86？我去，肯定支持
> 但有嘛用？局域网搭个毛线宝塔/v2ray

用上之后可以应该就可以访问ipv6网络了

**Comment by Lemonawa** [comment]
> > @dysf888 x86？我去，肯定支持
> > 但有嘛用？局域网搭个毛线宝塔/v2ray
> 
> 用上之后可以应该就可以访问ipv6网络了

teredo pls
